[[games]]
name="start"
content= """
<h1>You have to click "start"</h1>
<form action="/">
    <input type="submit" value="start" />
</form>
"""

[[games]]
name="demo"
content="""
<h1>demo game 1</h1>
<form action="/">
    <input type="submit" value="next" />
</form>
"""

[[games]]
name="demo2"
content="""
<h1>demo game 2</h1>
<form action="/">
    <input type="submit" value="next" />
</form>
"""

[[games]]
name="end"
content="""
<h1>You have to click "end"</h1>
<form action="/">
    <input type="submit" value="end" />
</form>
"""
