[leaderboard]
content = """
<h1>This is the leaderboard<h1>
<form action="/">
    <input type="submit" value="continue" />
</form>
"""

[privacy]
  [[privacy.intervals]]
  lower = 0
  upper = 42
  message = """
  privacy is between 0 and 42
  """
  [[privacy.intervals]]
  lower = 42
  upper = 100
  message = """
  privacy is between 42 and 100
  """

[time]
  [[time.intervals]]
  lower = 0
  upper = 69
  message = """
  time is between 0 and 69
  """



[[games]]
name="start"
content= """
<h1>You have to click "start"</h1>
<form action="/">
    <input type="submit" value="start" />
</form>
"""
congrat = 'this is a congrat'
message = 'this is another message'
fun_fact = 'this is a fun fact'

[[games]]
name="demo"
content="""
<h1>demo game 1</h1>
<form action="/">
    <input type="submit" value="next" />
</form>
"""

[[games]]
name="demo2"
content="""
<h1>demo game 2</h1>
<form action="/">
    <input type="submit" value="next" />
</form>
"""

[[games]]
name="end"
content="""
<h1>You have to click "end"</h1>
<form action="/">
    <input type="submit" value="end" />
</form>
"""
